#!/bin/sh
/usr/bin/conky -c  ./conkyrc;
/usr/bin/conky -c  ./memrc;
/usr/bin/conky -c  ./swaprc;
/usr/bin/conky -c  ./networkrc;
/usr/bin/conky -c  ./signalrc;
/usr/bin/conky -c  ./cpu0rc;
/usr/bin/conky -c  ./cpu15rc;
/usr/bin/conky -c  ./cpu26rc;
/usr/bin/conky -c  ./cpu37rc;
/usr/bin/conky -c  ./cpu48rc;
