#!/bin/bash
/usr/bin/conky -c  ~/.conky/conkyrc;
/usr/bin/conky -c  ~/.conky/memrc;
/usr/bin/conky -c  ~/.conky/swaprc;
/usr/bin/conky -c  ~/.conky/cpu0rc;
/usr/bin/conky -c  ~/.conky/cpu15rc;
/usr/bin/conky -c  ~/.conky/cpu26rc;
/usr/bin/conky -c  ~/.conky/cpu37rc;
/usr/bin/conky -c  ~/.conky/cpu48rc;
