#!/bin/sh
# This is a simple script that should allow the installation of a conky file
# to be simple and painfree. The idea is that once the user has cloned the git
# repository, a quick running of the setup script allows the ease of installation
# that many conky's seem hard to do.
echo "Setting up conky in the current user's home directory";
echo "${HOME}/.conky/ will be the conky configuration folder";
echo "----------------------------------------------------------------";
echo "WARNING!! This script assumes that all of the conky scripts to";
echo "be installed are in the parent directory !!";
echo "----------------------------------------------------------------";
echo "Proceed with setup? [y/n]";
read resp;
if [ $resp != 'y' ] 
	then
	echo "Setup aborted";
	exit;
fi;
echo "Proceeding with setup";
# Create the .conky/ in the home directory
mkdir ${HOME}/.conky;
# Move rcfiles over to the home folder -- 
cp ../*rc ${HOME}/.conky/;
cp ../lua/ ${HOME}/.conky/;
# Generate the conky start script
