#!/bin/sh
# This is a simple script that should allow the installation of a conky file
# to be simple and painfree. The idea is that once the user has cloned the git
# repository, a quick running of the setup script allows the ease of installation
# that many conky's seem hard to do.
printf "Setting up conky in the current user's home directory\n";
printf "${HOME}/.conky/ will be the conky configuration folder\n";
printf "----------------------------------------------------------------\n";
printf "WARNING!! This script assumes that all of the conky scripts to\n";
printf "be installed are in the parent directory !!\n";
printf "----------------------------------------------------------------\n";
printf "Proceed with setup? [y/n]";
read resp;
if [ $resp != 'y' ] 
	then
	printf "Setup aborted";
	exit;
fi;
printf "Proceeding with setup";
# Create the .conky/ in the home directory
mkdir ${HOME}/.conky;
# Move rcfiles over to the home folder -- 
cp ../*rc ${HOME}/.conky/;
cp ../lua/ ${HOME}/.conky/;
# Generate the conky start script
