#!/bin/sh
# This is a simple script that should allow the installation of a conky file
# to be simple and painfree. The idea is that once the user has cloned the git
# repository, a quick running of the setup script allows the ease of installation
# that many conky's seem hard to do.
printf "Setting up conky in the current user's home directory\n";
printf "${HOME}/.conky/ will be the conky configuration folder\n\n";
printf "WARNING!! This script assumes that all of the conky scripts to\n";
printf "be installed are in the parent directory !!\n\n";
printf "Proceed with setup? [y/n] ";
read resp;
if [ $resp != 'y' ] 
	then
	printf "Setup aborted";
	exit;
fi;
printf "Proceeding with setup\n";
# Create the .conky/ in the home directory
mkdir ${HOME}/.conky;
# Move rcfiles over to the home folder -- 
cp ../*rc ${HOME}/.conky/;
cp -R ../lua/ ${HOME}/.conky/;
# Generate the conky start script
touch ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/conkyrc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/memrc" 		>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/swaprc" 		>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/networkrc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/signalrc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/cpu0rc" 		>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/cpu15rc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/cpu26rc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/cpu37rc" 	>> ${HOME}/.start_conky;
echo "/usr/bin/conky -c ${HOME}/.conky/cpu48rc" 	>> ${HOME}/.start_conky;
chmod +x ${HOME}/.start_conky;
echo "complete"
