#!/bin/sh
echo "This will uninstall all files in ${HOME}/.conky/";
echo "Proceed? [y/n]";
read resp;
if [ $resp != 'y' ]
	then
	echo "Aborted";
	exit;
fi;
echo "Proceeding with removal";
rm -rf ${HOME}/.conky/;
echo "Complete";